[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "false"
  PUPPETEER_EXECUTABLE_PATH = "/opt/buildhome/.cache/puppeteer/chrome/linux-134.0.6998.35/chrome-linux64/chrome"
  CHROME_BIN = "/opt/buildhome/.cache/puppeteer/chrome/linux-134.0.6998.35/chrome-linux64/chrome"

[dev]
  targetPort = 5173
  port = 8888
  framework = "vite"
  functionsPort = 9999
  timeout = 60

# Handle JavaScript modules
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"

# Handle CSS
[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"

# Handle images
[[headers]]
  for = "/assets/*.{png,jpg,jpeg,gif,svg,ico}"
  [headers.values]
    Content-Type = "image/*"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000"
    Access-Control-Allow-Origin = "*"

# Handle SPA routes first
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Handle pre-rendered pages
[[redirects]]
  from = "/categorie/*"
  to = "/categorie/:splat/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/over-ons"
  to = "/over-ons/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/algemene-voorwaarden"
  to = "/algemene-voorwaarden/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/contact"
  to = "/contact/index.html"
  status = 200
  force = true

# Handle trailing slashes
[[redirects]]
  from = "/categorie/*/"
  to = "/categorie/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/over-ons/"
  to = "/over-ons"
  status = 301
  force = true

[[redirects]]
  from = "/algemene-voorwaarden/"
  to = "/algemene-voorwaarden"
  status = 301
  force = true

[[redirects]]
  from = "/privacy-policy/"
  to = "/privacy-policy"
  status = 301
  force = true

[[redirects]]
  from = "/contact/"
  to = "/contact"
  status = 301
  force = true

# Handle merchant feed
[[redirects]]
  from = "/feeds/merchant-products.xml"
  to = "/.netlify/functions/merchant-feed"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"

[functions.merchant-feed]
  timeout = 60
  memory = 1024