[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "false"
  PUPPETEER_EXECUTABLE_PATH = "/opt/buildhome/.cache/puppeteer/chrome/linux-134.0.6998.35/chrome-linux/chrome"
  CHROME_BIN = "/opt/buildhome/.cache/puppeteer/chrome/linux-134.0.6998.35/chrome-linux/chrome"

[dev]
  targetPort = 5173
  port = 8888
  framework = "vite"
  functionsPort = 9999
  timeout = 60

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { Not = [
    { Path = ["/categorie/*", "/over-ons", "/algemene-voorwaarden", "/privacy-policy", "/contact"] }
  ]}

[[redirects]]
  from = "/feeds/merchant-products.xml"
  to = "/.netlify/functions/merchant-feed"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"

[functions.merchant-feed]
  timeout = 60
  memory = 1024