[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/feeds/merchant-products.xml"
  to = "/.netlify/functions/merchant-feed"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"

[functions.merchant-feed]
  timeout = 10
  memory = 1024