[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/feeds/merchant-products.xml"
  to = "/feeds/merchant-products.xml"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"

[functions.generate-feed]
  schedule = "0 */1 * * *"  # Run every hour
  timeout = 10
  memory = 1024  # Increase memory allocation to 1GB
  background = true  # Allow the function to run in the background