[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "false"
  PUPPETEER_EXECUTABLE_PATH = "/opt/buildhome/.cache/puppeteer/chrome/linux-134.0.6998.35/chrome-linux64/chrome"
  CHROME_BIN = "/opt/buildhome/.cache/puppeteer/chrome/linux-134.0.6998.35/chrome-linux64/chrome"

[dev]
  targetPort = 5173
  port = 8888
  framework = "vite"
  functionsPort = 9999
  timeout = 60

# Handle assets first
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200
  force = true

# Handle sitemap
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Handle pre-rendered category pages
[[redirects]]
  from = "/categorie/*"
  to = "/categorie/:splat/index.html"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Handle pre-rendered static pages
[[redirects]]
  from = "/over-ons"
  to = "/over-ons/index.html"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/algemene-voorwaarden"
  to = "/algemene-voorwaarden/index.html"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy/index.html"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/contact"
  to = "/contact/index.html"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Handle SPA routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Handle merchant feed
[[redirects]]
  from = "/feeds/merchant-products.xml"
  to = "/.netlify/functions/merchant-feed"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"

[functions.merchant-feed]
  timeout = 60
  memory = 1024